### ISSUE TITLE
TOC is empty for ja-jp

### ISSUE THREAD

**Issue by 0giso** [aspnet/Docs.ja-jp#141]
TOC for ASP.NET Core ja-jp document is empty.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [ASP.NET Core の概要](https://docs.microsoft.com/ja-jp/aspnet/core/index?view=aspnetcore-2.2)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/docs.ja-jp/blob/live/aspnetcore/index.md)
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by 0giso** [comment]
I've reviewed a few pages. They all had the TOC correctly. Thanks for the fix.

**Comment by LisandroSu** [comment]
Thanks for checking, @0giso 

I'll be closing the Issue now.
