### ISSUE TITLE
TOC for ASP.NET Web Forms ja-jp document is empty.

### ISSUE THREAD

**Issue by hyoshioka0128** [aspnet/Docs.ja-jp#143]
TOC for ASP.NET Web Forms ja-jp document is empty.
Same as #141

**Comment by LisandroSu** [comment]
Hello, @hyoshioka0128 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/aspnet/identity/overview/getting-started/aspnet-identity-recommended-resources

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
