### ISSUE TITLE
TOC for ASP.NET Single Page Application ja-jp document is empty.

### ISSUE THREAD

**Issue by hyoshioka0128** [aspnet/Docs.ja-jp#149]
TOC for ASP.NET Single Page Application ja-jp document is empty.
Same as #141

**Comment by LisandroSu** [comment]
Hello, @hyoshioka0128

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #143. For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
