### ISSUE TITLE
does there exists --trust option?

### ISSUE THREAD

**Issue by npkk** [aspnet/Docs.ja-jp#219]
I'm seeing [this MVC tutorial](https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.2&tabs=visual-studio-code#feedback) and ran this command;
$ dotnet dev-certs https --trust
but I have got an error;
Specify --help for a list of available options and commands.
I did the command;
$ dotnet dev-certs https --help
so I found that, "dotnet dev-certs https" command does not have --trust option.
what is going on?

environments:
OS: Ubuntu 18.04
editor: VSCode
.net SDK version: 2.2.105

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [ASP.NET Core MVC の概要](https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs.ja-jp/blob/live/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hello, @npkk 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
