### ISSUE TITLE
コードスニペットが全て表示されていない

### ISSUE THREAD

**Issue by masaha03** [aspnet/Docs.ja-jp#54]
以下のページのコードスニペットが全て表示されていません。
https://docs.microsoft.com/ja-jp/aspnet/core/web-api/?view=aspnetcore-2.1

スニペットのシンタックス部分については、aspnet/Docsリポジトリの.mdファイルと差異は無かったので、ビルドプロセス上の問題でしょうか？

**Comment by gosali** [comment]
Hello, @masaha03 , 
  

Thank you for your feedback. 
 
We are actively reviewing your comments and will get back to you soon. 
 

Kind regards, 

Microsoft DOCS International Team

**Comment by masaha03** [comment]
修正済みのようなのでcloseします。
