### ISSUE TITLE
xrefリンクがURLに変換されていない

### ISSUE THREAD

**Issue by masaha03** [aspnet/Docs.ja-jp#80]
以下のページで、ソースのmarkdownでxrefで記述されているAPIドキュメントへのリンクが、URLに変換されていないため、APIドキュメントを参照することができません。
https://docs.microsoft.com/ja-jp/aspnet/core/fundamentals/routing?view=aspnetcore-2.1

**Comment by LisandroSu** [comment]
こんにちは、@ masaha03

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
こんにちは、@masaha03

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/aspnet/core/fundamentals/routing?view=aspnetcore-2.1  
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team
